demo4/bookgli/urls.py
from django.conf.urls import url

from . import views

app_name='bookgli'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^reader_login/$',views.reader_login,name='reader_login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^zhuce/$',views.zhuce,name='zhuce'),
    url(r'^reader/$',views.reader,name='reader'),
]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('bookgli/',include('bookgli.urls',namespace='bookgli'))
]

demo4/bookgli/models.py
from django.db import models

# Create your models here.

#用户
class Users(models.Model):
    uname=models.CharField(max_length=20,)
    upwd=models.CharField(max_length=20)
    #学院
    ucollege=models.CharField(max_length=20)
    unum=models.CharField(max_length=10)
    uemail=models.EmailField()

    def __str__(self):
        return self.uname


#图书表
class Books(models.Model):
    bname=models.CharField(max_length=30)
    bauthor=models.CharField(max_length=20)
    bpublish_com=models.CharField(max_length=30)
    bpublish_date=models.DateField()

    def __str__(self):
        return self.bname

#借阅历史表
class Histroys(models.Model):
    hbookid=models.ForeignKey('Books',on_delete=models.CASCADE)
    huserid=models.ForeignKey('Users',on_delete=models.CASCADE)
    hdate=models.DateTimeField(auto_now=True)
    hreturn=models.DateTimeField()
    hstatus=models.BooleanField(default=False)

demo4/bookgli/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse,HttpResponseRedirect

from .models import Users,Histroys,Books

# Create your views here.

# 首页
def index(request):
    return render(request,'bookgli/index.html')

# 读者登录
def reader_login(request):
    return render(request, 'bookgli/reader_login.html')

# 注册
def register(request):
    return render(request, 'bookgli/register.html')


#注册的跳转
def zhuce(request):
        uname=request.POST['username']
        passwd=request.POST['password']
        passwd2=request.POST['password2']
        college = request.POST['college']  # 学院
        number = request.POST['number']  # 学号
        email = request.POST['email']  # 邮箱
        listu=Users.objects.all().filter(uname=uname)
        # print(listu,type(listu),len(listu))
        if len(listu)==0:
            if passwd==passwd2:
                a1=Users()
                a1.uname=uname
                a1.upwd=passwd
                a1.ucollege=college
                a1.unum=number
                a1.uemail=email
                a1.save()
                return HttpResponseRedirect('/bookgli/reader_login/')
            else:
                pwd='Password mismatch'
                return HttpResponseRedirect('/bookgli/register/',{'error':pwd})
        else:
            pwd = 'User already exists'
            return HttpResponseRedirect('/bookgli/register/', {'error': pwd})


# 登录
def reader(request):
    users=request.POST['username']
    pwd=request.POST['password']
    listu = Users.objects.all().filter(uname=users,upwd=pwd )
    print(listu,len(listu))
    if len(listu)==0:
        error='Wrong account or password'
        return HttpResponseRedirect('/bookgli/reader_login/',{'error':error})
    else:
        ida=listu[0].id
        user=Users.objects.get(pk=ida)
        return render(request,'bookgli/reader.html',{'g':user})

demo4/templates/bookgli/index.html
{% extends "bookgli/layout.html" %}
{% block title %}主页{% endblock %}
{% block link %}
  <a href="#">管理员登录 </a>|
  <a href="{% url 'bookgli:reader_login' %}">读者登录 </a>
{% endblock %}

{% block body %}
  <h2>欢迎使用</h2>
{% endblock %}

demo4/templates/bookgli/layout.html
<!doctype html>
<title> {% block title %} 图书管理系统 {% endblock %} </title>
<link rel=stylesheet  href="../../static/css/style.css">
<div class=page>
  <h1>图书管理系统</h1>
  <div class=navigation>
    {% block link %}{% endblock %}
  </div>
  <div class=body>
    {% block body %}{% endblock %}
   </div>
  <div class=footer>
     &mdash; 华中科技大学
  </div>
</div>
    

demo4/templates/bookgli/reader.html
{% extends 'bookgli/layout.html' %}
{% block title %} 欢迎使用 {% endblock %}
{% block link %} 
	<a href="{% url 'bookgli:index' %}"> 注销[{{g.uname}}] </a> |
	<a href="#"> 查询 </a> |
	<a href="#"> 查看个人信息 </a> |
	<a href="#"> 查看阅读记录 </a>

{% endblock %}

{% block body %}
	<h2> 欢迎使用 </h2>
{% endblock %}

demo4/templates/bookgli/reader_login.html
{% extends "bookgli/layout.html" %}
{% block title%} 读者登录 {% endblock%}
{% block link%}
	<a href="{% url 'bookgli:index' %}"> 返回   </a>|
	<a href="{% url 'bookgli:register' %}"> 注册 </a>
{% endblock%}
{% block body %}
	<h2> 读者登录 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif%}
	<form action="{% url 'bookgli:reader' %}" method=post>
	  <dl>
	    <dt>用户名: </dt>
	    <dd><input type=text name=username size=30 value=""> </dd>
	    <dt>密码:	 </dt>
	    <dd><input type=password name=password size=30> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="登录">
	  </div>
	</form>
{% endblock %}

demo4/templates/bookgli/register.html
{% extends "bookgli/layout.html" %}
{% block title %} 注册 {% endblock %}
{% block link %} 
	<a href="{% url 'bookgli:reader_login' %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'bookgli:zhuce' %}" method=post>
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 value=""> </dd>
	    <dt>密码:</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>密码<small>(重复)</small>:	</dt>
	    <dd><input type=password name=password2 size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30> </dd>
	  </dl>
	  <div class=actions><input type=submit value="注册"></div>
	</form>

{% endblock %}